language:
  node_js
install:
  - npm install -g codecov
node_js:
  - "12"
  - "10"
  - "9"
  - "8"
  - "7"
  - "6"
script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov
cache:
  directories:
    - node_modules
