language:
  node_js
node_js:
  - "13"
  - "12"
  - "10"
  - "9"
script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && codecov
cache:
  directories:
    - node_modules
